title: 鱼跃
email: fleapus@gmail.com
description: Ivy League支持|中美两国导师|招生官标准|深度交流，留美咨询，文书修改，倾心帮助考虑赴美深造的中国学子，把握人生转折点。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
